added option to show rating count in category view
plentymarkets/feedback-plugin pull request #171
Opened 2022-12-14 08:06 UTC by MaxBentz

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/plentyshop

2022-12-14 08:08 UTC, MaxBentz commented
@sene-plenty ready for review :)

2022-12-30 14:38 UTC, stentrop requested changes

2022-12-30 14:38 UTC, stentrop commented on resources/views/DataProvider/CategoryAverageRating.twig
> +            <span>({{ Twig.print('counts.ratingsCountTotal') }})</span>
The TwigBuilder is wrong here. No output is generated.

```suggestion
            <span>({{ counts.ratingsCountTotal }})</span>
```

2023-01-03 12:55 UTC, Tim-M-S requested changes
<img width="254" alt="image" src="https://user-images.githubusercontent.com/11943448/210360929-a73ff4b2-ad05-4ab2-a1e2-debf7d5f17e6.png">
If the option showRatingCountInCategoryView is active you have to set a class to the stars divs and offset them by x px

2023-01-06 08:27 UTC, MaxBentz commented
Class has been added. New build have to be made

2023-01-06 11:56 UTC, Tim-M-S commented on resources/css/main.scss
> +        top: 1px;
```suggestion
        top: -1px;
```

2023-01-06 11:56 UTC, Tim-M-S submitted a review, later dismissed

2023-01-06 11:57 UTC, Tim-M-S commented on resources/lang/en/Config.properties
> +showRatingCountInCategoryViewLabel=Show number of article ratings in the category view
```suggestion
showRatingCountInCategoryViewLabel=Show number of reviews in the category view
```

2023-01-06 11:58 UTC, Tim-M-S submitted a review, later dismissed

2023-01-06 12:11 UTC, Tim-M-S commented on resources/css/main.scss
> +        left: 88px;
```suggestion
        right: -20px
```

2023-01-09 10:01 UTC, stentrop approved these changes

2023-01-09 10:01 UTC, merged